# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wenet.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bwenet.proto\x12\x05wenet\"\xb1\x01\n\x07Request\x12\x34\n\rdecode_config\x18\x01 \x01(\x0b\x32\x1b.wenet.Request.DecodeConfigH\x00\x12\x14\n\naudio_data\x18\x02 \x01(\x0cH\x00\x1aH\n\x0c\x44\x65\x63odeConfig\x12\x14\n\x0cnbest_config\x18\x01 \x01(\x05\x12\"\n\x1a\x63ontinuous_decoding_config\x18\x02 \x01(\x08\x42\x10\n\x0eRequestPayload\"\xed\x02\n\x08Response\x12&\n\x06status\x18\x01 \x01(\x0e\x32\x16.wenet.Response.Status\x12\"\n\x04type\x18\x02 \x01(\x0e\x32\x14.wenet.Response.Type\x12&\n\x05nbest\x18\x03 \x03(\x0b\x32\x17.wenet.Response.OneBest\x1aI\n\x07OneBest\x12\x10\n\x08sentence\x18\x01 \x01(\t\x12,\n\nwordpieces\x18\x02 \x03(\x0b\x32\x18.wenet.Response.OnePiece\x1a\x34\n\x08OnePiece\x12\x0c\n\x04word\x18\x01 \x01(\t\x12\r\n\x05start\x18\x02 \x01(\x05\x12\x0b\n\x03\x65nd\x18\x03 \x01(\x05\"\x1c\n\x06Status\x12\x06\n\x02ok\x10\x00\x12\n\n\x06\x66\x61iled\x10\x01\"N\n\x04Type\x12\x10\n\x0cserver_ready\x10\x00\x12\x12\n\x0epartial_result\x10\x01\x12\x10\n\x0c\x66inal_result\x10\x02\x12\x0e\n\nspeech_end\x10\x03\x32\x39\n\x03\x41SR\x12\x32\n\tRecognize\x12\x0e.wenet.Request\x1a\x0f.wenet.Response\"\x00(\x01\x30\x01\x42\x11\n\x07\x65x.grpc\xa2\x02\x05wenetb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'wenet_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\007ex.grpc\242\002\005wenet'
  _REQUEST._serialized_start=23
  _REQUEST._serialized_end=200
  _REQUEST_DECODECONFIG._serialized_start=110
  _REQUEST_DECODECONFIG._serialized_end=182
  _RESPONSE._serialized_start=203
  _RESPONSE._serialized_end=568
  _RESPONSE_ONEBEST._serialized_start=331
  _RESPONSE_ONEBEST._serialized_end=404
  _RESPONSE_ONEPIECE._serialized_start=406
  _RESPONSE_ONEPIECE._serialized_end=458
  _RESPONSE_STATUS._serialized_start=460
  _RESPONSE_STATUS._serialized_end=488
  _RESPONSE_TYPE._serialized_start=490
  _RESPONSE_TYPE._serialized_end=568
  _ASR._serialized_start=570
  _ASR._serialized_end=627
# @@protoc_insertion_point(module_scope)
